
# Enables best HW decoder; turn off for software decoding
hwdec=auto

# Saves the seekbar position on exit
save-position-on-quit=yes

# Only plays youtube videos till 1080p and with h264 codec
ytdl-format=bestvideo[height<=?1080][vcodec^=avc1]+bestaudio/best
