[FileDialog]
history=file:///home/monochrome/Downloads, file:///home/monochrome/.config, file:///home/monochrome/.config/ranger, file:///home/monochrome/Videos/Screencasts, file:///home/monochrome/Videos, file:///home/monochrome/Pictures
lastVisited=file:///home/monochrome/Pictures
qtVersion=5.15.9
shortcuts=file:, file:///home/owo
sidebarWidth=87
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xba\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xaa\0\0\0\x1\0\0\0\0\0\0\0m\0\0\0\x1\0\0\0\0\0\0\0=\0\0\0\x1\0\0\0\0\0\0\0\x66\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)"
viewMode=Detail
